n1,n2 = input ("enter vlues : ").split(" ",2)
n1 = int(n1)
n2 = int(n2)

print("***************  Bit wise  ******************")
print("n1 & n2 = " , (n1 & n2))
print("n1 | n2 = " , (n1 | n2))
print("n1 ^ n2 = " , (n1 ^ n2))
print("n1 >> n2 = " , (n1 >> n2))
print("n1 << n2 = " , (n1 << n2))
print("not n1 = " , (~n1))
print("\n******************* Arithmetic ****************\n")

print("n1 + n2 = " , (n1 + n2))
print("n1 - n2 = " , (n1 - n2))
print("n1 * n2 = " , (n1 * n2))
print("n1 / n2 = " , (n1 / n2))
print("n1 % n2 = " , (n1 % n2))
print("*********************************************\n")